#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kiwisolver
Version  : 1.0.1
Release  : 1
URL      : https://pypi.python.org/packages/31/60/494fcce70d60a598c32ee00e71542e52e27c978e5f8219fae0d4ac6e2864/kiwisolver-1.0.1.tar.gz
Source0  : https://pypi.python.org/packages/31/60/494fcce70d60a598c32ee00e71542e52e27c978e5f8219fae0d4ac6e2864/kiwisolver-1.0.1.tar.gz
Summary  : A fast implementation of the Cassowary constraint solver
Group    : Development/Tools
License  : BSD-3-Clause
Requires: kiwisolver-python3
Requires: kiwisolver-python
Requires: setuptools
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
===============

%package python
Summary: python components for the kiwisolver package.
Group: Default
Requires: kiwisolver-python3

%description python
python components for the kiwisolver package.


%package python3
Summary: python3 components for the kiwisolver package.
Group: Default
Requires: python3-core

%description python3
python3 components for the kiwisolver package.


%prep
%setup -q -n kiwisolver-1.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522173785
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
